field1: "**Always available:**"
field1value:
  - "游릴 Fireballs"
  - "游릴 Ladders"
  - "游릴 Silverfish"
  - "游릴 Blue side [4v4 Only]"
  - "游릴 Diamond Armor"
  - "游릴 Diamond Sword"
  - "Anything else not listed under the restricted or banned items is allowed"

field2: "**Available after one bed is broken:**"
field2value:
  - "游릳 Water"
  - "游릳 All pots"
  - "游릳 Pearls"
  - "游릳 KB Sticks"
  - "游릳 Both sides"

field3: "**Banned items:**"
field3value:
  - "游린 Golems"
  - "游린 All bows"
  - "游린 Obsidian"
